### ISSUE TITLE
Demo details are incorrect

### ISSUE THREAD

**Issue by projx** [viewflow/cookbook#10]
Hi

It seems the path details shown on https://github.com/viewflow/viewflow/tree/master/demo are incorrect, it shows:

tox loaddata tests/helloworld/fixtures/default_data.json
tox loaddata tests/shipment/fixtures/default_data.json

But these files appear incorrect, should the test/ be replaced with demo/?

**Comment by kmmbvnr** [comment]
Thanks fixed
