### ISSUE TITLE
Column title for composite key

### ISSUE THREAD

**Issue by lfpertile** [viewflow/cookbook#102]
It would be nice if CompositeKey column names refer to model fields instead of database column names. In a legacy database name could be far from today standars. When I tried to use I had to use real column name in CompositeKey, if I use my "new" model name (Django standard) it complains because the column doesn't exist. So I used database column name in model name which makes less clear my code because I'm referring to a related entity by its foreign key instead of my "pretty Django" name.

**Comment by omid-hoseini** [comment]
I have the same problem. unfortunately my database column name contain space on it, so i can't use it for model name. anyone know how can i fix it?

**Comment by kmmbvnr** [comment]
It's not clear for me, what is the problem with column names. Django has db_column property, that can be used as usual with fields definition, where as in the Django code, the Django field names are used to refer to the Django fields

```sql
CREATE TABLE example_table (
    Column_One INTEGER,
    "Column Two" INTEGER,
    Another_Column INTEGER,
    PRIMARY KEY (Column_One, "Column Two")
);
```

```python
from django.db import models

from viewflow.fields import CompositeKey

class Example(models.Model):
    id = CompositeKey(columns=['column_one', 'column_two'])
    column_one = models.IntegerField()
    column_two = models.IntegerField(db_column="column two")
    another_column = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'example_table'
````
