### ISSUE TITLE
Not able to install django-viewflow-pro==1.4.1

### ISSUE THREAD

**Issue by techlearner96** [viewflow/cookbook#104]
I cloned the respository. And run pip install -r requirements.txt , but it gives me error
ERROR: Could not find a version that satisfies the requirement django-viewflow-pro==1.4.1 (from versions: none)
ERROR: No matching distribution found for django-viewflow-pro==1.4.1

How to use viewflo-pro?

**Comment by kmmbvnr** [comment]
Hi Viewflow PRO is the distribution available for commercial customers only http://viewflow.io
