### ISSUE TITLE
Need some top margin on .vf-form-row to account for help text, especially on mobile

### ISSUE THREAD

**Issue by jturmel** [viewflow/cookbook#129]
Current behavior (v2):
<img width="422" alt="CleanShot 2023-08-16 at 13 38 44@2x" src="https://github.com/viewflow/cookbook/assets/37833/aa280f9b-8f73-48ff-9788-23559df3511d">

Desired behavior (v2):
<img width="460" alt="CleanShot 2023-08-16 at 13 48 30@2x" src="https://github.com/viewflow/cookbook/assets/37833/4576ed2e-136a-47cf-bc94-198f247e81c4">

**Comment by kmmbvnr** [comment]
Fixed, in a git version.

Caused also by fixed 'height' property
