### ISSUE TITLE
Helloworld workflow does not show up 

### ISSUE THREAD

**Issue by fr33l4ncer** [viewflow/cookbook#13]
After folowing quickstart tutorial http://docs.viewflow.io/viewflow_quickstart.html i cant see helloworld workflow 
Clicking on processes do nothing (not even any Debug message) 
Python 3.7.0
Django==2.1.1
django-filter==2.0.0
django-material==1.3.0
django-viewflow==1.3.0
pytz==2018.5

**Comment by kmmbvnr** [comment]
That's hard to say what happens in your case. Please check that you have added @frontend.register in the helloworld/flows.py
![workflow django material](https://user-images.githubusercontent.com/282529/45075477-0e726480-b109-11e8-85fb-abbc9ff97b7c.png)

**Comment by fr33l4ncer** [comment]
I did. i followed up documentation exactly.

**Comment by kmmbvnr** [comment]
Probably you miss some part.

You could check cookbook/helloworld code sample for a reference.

**Comment by fr33l4ncer** [comment]
You're right i have applied fronted.register decorator but  missed  frontend import . i have not experienced any error messages hence my confusion
