### ISSUE TITLE
custom middleware question

### ISSUE THREAD

**Issue by ajcypherint** [viewflow/cookbook#19]
Why does this line just RETURN and not call then next middlware at least?
Are you not going to be skipping a RSAA call here?

https://github.com/viewflow/cookbook/blob/650fee5a88fb89be475c64c5342ac1cab6762200/_articles/redux_jwt_auth/frontend/src/middleware.js#L36

**Comment by kmmbvnr** [comment]
mm, yep. it's postponed

**Comment by guzzijones** [comment]
I am finding that if i use redux-thunk with an async function and i leave this line in i am throwing an u defineded exception.  If i instead just call ghe postponed function i do see a double token refresh but it works.
