### ISSUE TITLE
cookbook react_ui backend requirements error 

### ISSUE THREAD

**Issue by ibrahimroshdy** [viewflow/cookbook#37]
### ERROR
 ```
ERROR: Invalid requirement: 'pyaml=3.13' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```
```
ModuleNotFoundError: No module named 'celery'
```

django==2.1.2
djangorestframework==3.9.0
django-rest-swagger==2.2.0
 **was** `pyaml=3.13` **change to** `pyaml==3.13`
django-viewflow-pro==1.4.1
django-material-pro==1.4.1
**added** celery

**Comment by kmmbvnr** [comment]
Thanks for the notice!

The whole sample outdated these days and was removed
