### ISSUE TITLE
Фигурные скобки лишние

### ISSUE THREAD

**Issue by ibooj** [viewflow/cookbook#4]
https://github.com/viewflow/cookbook/blob/25f93267d59169005a5ea1fb97a7dbe7d4fcd2cc/_articles/redux_jwt_auth/frontend/src/components/LoginForm.js#L33

**Comment by kmmbvnr** [comment]
No, that's deconstruction operator.

**Comment by ibooj** [comment]
я поторопился, вот так `const errors = this.props.errors || {}` работает

**Comment by ibooj** [comment]
а так `const {errors} = this.props` ошибка, `Unhandled Rejection (TypeError): Cannot read property 'non_field_errors' of undefined`

**Comment by kmmbvnr** [comment]
mm, yep, indeed. Fixed!

Thanks!

**Comment by ibooj** [comment]
юавелкам)
