### ISSUE TITLE
Action on_delete needed

### ISSUE THREAD

**Issue by lantonov** [viewflow/cookbook#5]
In the Blood Test model (model.py) classes BloodSample, Biochemistry, TumorMarkers, Hormones, BloodTestProcess require a second argument on_delete = for ForeignKey() and OneToOneField() functions

**Comment by kmmbvnr** [comment]
Thanks for the notice, I need to update cookbook for Django 2.0

**Comment by lantonov** [comment]
I suppose it is on_delete=models.CASCADE

**Comment by kmmbvnr** [comment]
Updated
