### ISSUE TITLE
Middleware clean-up error introduced

### ISSUE THREAD

**Issue by mpdrsn** [viewflow/cookbook#7]
First, I really appreciate your work on this! That said, I'm very new to JS and know very little about securing logins, but on your last push, when line 20 was added to middleware.js, `postponedRSAAs = []` attempts to reallocate a _constant array_...and fails when compiled. Although slightly slower, I think that this can be avoided with `postponedRSAAs.length = 0`

**Comment by kmmbvnr** [comment]
Yeah, thanks for noticing!
